//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycheb_practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ID { get; set; }
        public Nullable<int> Tip_ID { get; set; }
        public Nullable<int> brand_ID { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> Config_ID { get; set; }
        public Nullable<int> Characteristics_ID { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Characteristics Characteristics { get; set; }
        public virtual Config Config { get; set; }
        public virtual Tip Tip { get; set; }
    }
}
