//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycheb_practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_View
    {
        public int ID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> brand_ID { get; set; }
        public string Brand_Name { get; set; }
        public Nullable<int> Tip_ID { get; set; }
        public string Tip_Name { get; set; }
        public Nullable<int> Config_ID { get; set; }
        public string Config_Name { get; set; }
        public Nullable<int> Characteristics_ID { get; set; }
        public string Dimensions { get; set; }
        public Nullable<int> Wheels { get; set; }
        public Nullable<int> Frame { get; set; }
        public Nullable<int> Gearbox { get; set; }
    }
}
